### ISSUE TITLE
Feature Request: pass Svelte Component inside InterActiveTab component body

### ISSUE THREAD

**Issue by Gildedter** [shinokada/flowbite-svelte#18]
Thank you for sharing the library, just wanted to ask if it this could be added.

I had to base it on the included [interactive tab](https://github.com/shinokada/flowbite-svelte/blob/6053bad6e08582bda616e3022607aa9d0995e7b9/src/lib/tabs/InteractiveTabs.svelte), not really sure if someone else might need it, its not a very pretty implementation but it works.

```
<div id="{tabId}Content">
    {#each tabs as { label, content, id }}
        {#if activeTabValue === id}
            <div
                class="p-4 bg-gray-50 rounded-lg dark:bg-gray-800"
                id={label}
                role="tabpanel"
                aria-labelledby="{label}-tab"
            >
                {#if typeof content === 'string'}
                    <p class="text-sm text-gray-500 dark:text-gray-400">
                        {content}
                    </p>
                {:else}
                    <svelte:component this={content} />
                {/if}
            </div>
        {/if}
    {/each}
</div>
```

**Comment by shinokada** [comment]
Can I ask what kind of svelte component you are planning use? If you can give me an example, it will be helpful.

**Comment by Gildedter** [comment]
I'm nesting this inside a modal, as a sort of per table item menu.

i.e.
Table:
>Rows
    >(column) Edit Button Modal
          >XL Modal
                >Interactive Tab as a tabbed menu of sorts
                    >Individual Svelte Component Forms that hold menu items

**Comment by shinokada** [comment]
I just modified it for the svelte components. 
You can see an example [here](https://flowbite-svelte.vercel.app/tests/tab).
Please update npm:

```
npm i -D flowbite-svelte@latest
```

Also please change your key name from title to name. After adding TS, I changed some of key names. Sorry.

```
interface InteractiveTabType {
    name: string;
    id: number;
    content: string | typeof SvelteComponent;
}
```

**Comment by Gildedter** [comment]
Thank you for the quick update, will update versions now.

**Comment by shinokada** [comment]
In the future version, the Interactive tab component change the structure. It will use `slot` so you can add another component or HTML etc. So it will be a BREAKING CHANGE.
The reason behind this change is to make the component more flexible. By using the `slot`, uses can add anything in the slot.

**Comment by shinokada** [comment]
I leave the `InteractiveTabs` component as it is. And I just added `InteractiveTabHead` and `TabContent` components. It makes easy to add anything in the tab.
[Demo](https://flowbite-svelte.vercel.app/tabs/interactive-tabs-2)
