### ISSUE TITLE
Logo class for Navbar Component

### ISSUE THREAD

**Issue by Gildedter** [shinokada/flowbite-svelte#21]
Having trouble sizing my logo (its a .png, its taking up the entire screen...) on the Navbar Component, missing property for image sizing.

Sidebar component's logo has its default class already set, any chance for customization (for both components' `logo` elements)?

**Comment by shinokada** [comment]
The [`navbar`](https://flowbite-svelte.vercel.app/navbars/default0 component has `spanClass` and `navClass` to control the style.

Can you try something like this:

```
<script>
let website = {
		sitename: 'My website',
		alt: 'My-website'
	};
	let navbar = {
		logo: '/images/mylogo.png',
		textsize: 'text-lg',
		spanClass:
			'self-center text-2xl pl-2 font-semibold text-gray-900 whitespace-nowrap dark:text-white',
		navClass: 'py-2 px-16 bg-white border-gray-200 dark:bg-gray-700 dark:border-gray-700'
	};

	let menus = [
		{
			name: 'Home',
			href: '/'
		},
		{
			name: 'About',
			href: '/about'
		},
		{
			name: 'Contact',
			href: '/contact'
		}
	];
</script>
<Navbar {...website} {...navbar} {menus} />
```

**Comment by shinokada** [comment]
I close this for now. If you have any more problems, feel free to comment again.
