### ISSUE TITLE
Modal component contents don't scroll

### ISSUE THREAD

**Issue by gushogg-blake** [shinokada/flowbite-svelte#23]
If a modal's content is longer than the page, it gets clipped and there is no vertical scrollbar.  Suggested solution: make the backdrop (the translucent div) the parent of the modal div and give it `overflow-y: auto`.  Would also require `stopPropagation` for clicks on the modal as they would propagate to the parent and close the modal otherwise.  If this solution sounds good I can make a PR. Thanks!

**Comment by gushogg-blake** [comment]
Example:

```diff
diff --git a/src/lib/modals/MediumModal.svelte b/src/lib/modals/MediumModal.svelte
index cb2b5db..9b16ed3 100644
--- a/src/lib/modals/MediumModal.svelte
+++ b/src/lib/modals/MediumModal.svelte
@@ -168,14 +168,17 @@
 </script>
 
 {#if showModalId === id}
-    <!-- Main modal -->
     <div
-        {id}
-        role="dialog"
-        aria-modal="true"
-        class="flex overflow-y-auto overflow-x-hidden fixed right-0 left-0 top-20 z-50 justify-center items-center"
+        on:click={closeModal}
+        class="bg-gray-900 bg-opacity-50 dark:bg-opacity-80 fixed inset-0 z-40 w-full h-full overflow-auto"
     >
-        <div class="relative px-4 w-full max-w-2xl h-full md:h-auto">
+        <!-- Main modal -->
+        <div
+            on:click|stopPropagation={() => {}}
+            role="dialog"
+            aria-modal="true"
+            class="mx-auto my-20 px-4 w-full max-w-2xl h-full md:h-auto"
+        >
             <!-- Modal content -->
             <div class={divClass}>
                 <!-- Modal header -->
@@ -217,9 +220,4 @@
             </div>
         </div>
     </div>
-
-    <div
-        on:click={closeModal}
-        class="bg-gray-900 bg-opacity-50 dark:bg-opacity-80 fixed inset-0 z-40 w-full h-full"
-    />
 {/if}
```

**Comment by gushogg-blake** [comment]
(flex also has issues with scrolling and `align-items: center`, so this just uses `margin: auto` for horizontal centering)

**Comment by shinokada** [comment]
I never thought putting a content longer than a page. As far as it works, a PR is welcome.

**Comment by shinokada** [comment]
Flex has another issue. You can't close a modal when you click the sides of the modal since it takes the area. You can close a modal when you click under/above the modal. If it is possible, a modal without flex is better solusion.

**Comment by Gildedter** [comment]
Need help with modal's buttons, they're required by default even when I don't want to display any buttons on them, issue persists on all modal sizes
