### ISSUE TITLE
Navbar - hide logo

### ISSUE THREAD

**Issue by troncomputers** [shinokada/flowbite-svelte#30]
What should I do if I don't want logo in `Navbar`?

![logo_flow_bite](https://user-images.githubusercontent.com/29543667/163398950-5572ec70-80f0-4180-a5ab-79cb5c15f265.png)

**Comment by shinokada** [comment]
You can add an empty string:

```
<script>
...
let siteName = "";
let logo = "";
let alt = "";
</script>

<Navbar {siteName} {alt} {logo} />
```

**Comment by troncomputers** [comment]
Still giving the same result.

**Comment by troncomputers** [comment]
Ok, I did not add `{alt}`. With only `{logo}` (without alt) gives same result.
