### ISSUE TITLE
Build errors after updating to v 0.14.0

### ISSUE THREAD

**Issue by Gildedter** [shinokada/flowbite-svelte#39]
After updating (`npm i -D flowbite-svelte@latest`), I'm getting a `[plugin:vite:css] Cannot find module 'flowbite/plugin'` when I'm building my app, I've tried deleting both `package-lock.json` and `node_modules` then running `npm install`

**Comment by Gildedter** [comment]
along with this error
```
/ClientApp/node_modules/flowbite-svelte/accordions/AccordionItem.svelte
  40 |  const { Object: Object_1 } = globals;
  41 |  import { getContext } from 'svelte';
  42 |  import collapse from 'svelte-collapse';
     |                        ^
  43 |
  44 |  import {
```

**Comment by shinokada** [comment]
Can you run the followings and let me know:

```
npm i -D svelte-collapse flowbite
```

**Comment by Gildedter** [comment]
Working now, also ran `npm i -D @codewithshin/svelte-heroicons` for it to build completely, thanks for the quick response.

**Comment by shinokada** [comment]
I close the issue for now. If you have any problem, let me know.

**Comment by shinokada** [comment]
If you are using simle-icons, please install it too. I didn't put it under the dependencies.

```
npm i @codewithshin/svelte-simpleicons
```

**Comment by shinokada** [comment]
I will put back `flowbite` and `svelte-collapse` to the dependencies.
I will keep heroicons and simple-icons under the dev dependencies, in order to keep small file sizes/numbers.

**Comment by Gildedter** [comment]
I'm using [Iconify for Svelte](https://github.com/iconify/iconify/tree/master/packages/svelte), my work around is creating a component wrapper for a specific icon and then passing that as the icon for other svelte components i.e. `flowbite-svelte Sidebar`
